// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXgfrg_ej8y7HrjMMKaWv7jqXbOYF_jo',
    appId: '1:518306560331:web:dffff23a27918349a210ce',
    messagingSenderId: '518306560331',
    projectId: 'revised-mobile-assignment',
    authDomain: 'revised-mobile-assignment.firebaseapp.com',
    storageBucket: 'revised-mobile-assignment.appspot.com',
    measurementId: 'G-QGT2QSZXQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLVZ0kPWifGRjqssoMDZe1dwGjfsQQfo',
    appId: '1:518306560331:android:9003177ae17ec49da210ce',
    messagingSenderId: '518306560331',
    projectId: 'revised-mobile-assignment',
    storageBucket: 'revised-mobile-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_3msd_892WfDmMoEG6XIgiYSmcE4iek',
    appId: '1:518306560331:ios:b48e7733f2741a4da210ce',
    messagingSenderId: '518306560331',
    projectId: 'revised-mobile-assignment',
    storageBucket: 'revised-mobile-assignment.appspot.com',
    androidClientId: '518306560331-s39fh9a66kstj2k1jnjq28skp17cs7t3.apps.googleusercontent.com',
    iosClientId: '518306560331-cee9v581kcqc7v158bl9jbojabn47q54.apps.googleusercontent.com',
    iosBundleId: 'com.assignment.revisedMobileAssignment',
  );
}
